name: Build Demo

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Build
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      -
        name: npm install and build
        run: |
          npm i
          npm run build
      -
        name: Move files
        if: success()
        run: |
          sh ./postdeploy.sh
      -
        name: Deploy
        if: success()
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
